### ISSUE TITLE
Open as Administrator Brings No Action

### ISSUE THREAD

**Issue by willysr** [mate-desktop-legacy-archive/mate-file-manager-gksu#4]
I have built mate-file-manager-gksu along with libgksu from nongnu.org and restarted MATE and i can confirm that context menu of opening as administrator does show up, but when i selected a file and open it using administrator, it doesn't do anything

any ideas?

**Comment by stefano-k** [comment]
Do you have gksu binary?

```
$ which gksu
/usr/bin/gksu
```

**Comment by willysr** [comment]
OK, i missed that one since i thought mate-file-manager-gksu provides this one
OK, my next question is which one does this extension support?
I found 2 version of gksu:
http://www.nongnu.org/gksu/ and https://live.gnome.org/gksu

**Comment by stefano-k** [comment]
The extension just call the "gksu" binary, so I think both are ok

**Comment by willysr** [comment]
OK, thanks, marking it closed

**Comment by stefano-k** [comment]
:+1:
